//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Muniamfc.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_MUNIA_MFC_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_Realtime             147
#define IDD_DIALOG_SVO_reading          149
#define IDD_DIALOG_Measurements         151
#define IDD_DIALOG_M_setting            153
#define IDD_DIALOG_SVO_Record           155
#define IDB_BITMAP1                     159
#define IDD_DIALOG_progressBar          167
#define IDD_DIALOG_Ucalibration         169
#define IDD_DIALOG_input                171
#define IDC_B_Camera_Open               1000
#define ID_Exit                         1001
#define IDC_B_Close_Camera              1002
#define IDC_B_Calculation               1003
#define IDC_B_Calculation_flexiPoints   1003
#define IDC_B_calibration               1004
#define IDC_B_Select_Points             1005
#define IDC_B_refresh                   1007
#define IDC_Button_Calculation          1007
#define IDC_Right                       1008
#define IDC_Left                        1009
#define IDC_Realtime                    1013
#define IDC_Recorded                    1014
#define IDC_Edit_filename               1015
#define IDC_B_enter                     1017
#define IDC_Edit_Filename1              1018
#define IDC_B_Record_svo                1020
#define IDC_SVO_recording               1021
#define IDC_B_opening_recording         1021
#define IDC_svo_path_0                  1022
#define IDC_svo_path_1                  1023
#define IDC_CapNo                       1024
#define IDC_caono                       1025
#define IDC_Using_frame_from            1026
#define IDC_B_closing_recording         1026
#define IDC_Using_frame_to              1027
#define IDC_starting_frame_no           1028
#define IDC_ending_frame_no             1029
#define IDC_Bilateral_Filter            1030
#define IDC_Median_Blur                 1031
#define IDC_Gaussian_Blur               1032
#define IDC_string_lowerlimit           1033
#define IDC_filter_ksize                1034
#define IDC_Edit_ksize                  1035
#define IDC_setting_calculation         1036
#define IDC_string_upperlimit           1036
#define IDC_B_Confirm_setting           1037
#define IDC_Calibrated_U                1038
#define IDC_STATIC_select_points        1039
#define IDC_STATIC_confirm_setting      1040
#define IDC_STATIC_press_enter          1041
#define IDC_STATIC_press_RecordSVO      1042
#define IDC_STATIC_openCamera           1043
#define IDC_STATIC_pressCalculatio      1044
#define IDC_STATIC_pressCloseCamera     1045
#define IDC_setting_camera              1045
#define IDC_STATIC_filterOption         1046
#define IDC_STATIC_SelectMirror         1047
#define IDC_STATIC_selectCamera         1048
#define IDC_STATIC_bitmap               1051
#define IDC_CHECK1                      1052
#define IDC_CHECK_preview               1052
#define IDC_CHECK_userNote              1052
#define IDC_CHECK_automatic             1052
#define IDC_CHECK_manual                1052
#define IDC_ideal_position_mirror       1052
#define IDC_CHECK_CameraSettings        1053
#define IDC_R_HD1080                    1054
#define IDC_R_HD2K                      1055
#define IDC_S_Resolution                1058
#define IDC_S_DepthMode                 1059
#define IDC_R_ULTRA                     1064
#define IDC_R_QUALITY                   1065
#define IDC_R_PERFORMANCE               1066
#define IDC_R_LAST                      1067
#define IDC_R_STANDARD                  1070
#define IDC_R_FILL                      1071
#define IDC_E_Gain0                     1072
#define IDC_E_Exposure0                 1073
#define IDC_E_Gain1                     1074
#define IDC_E_Exposure1                 1075
#define IDC_STATIC_Gain                 1076
#define IDC_STATIC_Exposure             1077
#define IDC_STATIC_camL                 1078
#define IDC_STATIC_camR                 1079
#define IDC_CHECK_3D_data               1080
#define IDC_BUTTON_3dData               1081
#define IDC_BUTTON_example              1088
#define IDC_BUTTON_refreshData          1094
#define IDC_BUTTON_mSettings            1095
#define IDC_RADIO_svo_recording         1098
#define IDC_BUTTON_start                1099
#define IDC_BUTTON_goMeasementDialog    1100
#define IDC_STATIC_mainDlgBG            1102
#define IDC_STATIC_pMeasurementBG       1103
#define IDC_PROGRESS2                   1117
#define IDC_PROGRESS1                   1118
#define IDC_EDIT_userNote               1119
#define IDC_BUTTON_cancel               1120
#define IDC_BUTTON_take_U               1121
#define IDC_BUTTON_combile_U            1122
#define IDC_EDIT_takeInput              1123
#define IDC_BUTTON_change_Ucsv          1123
#define IDC_BUTTON3                     1126
#define IDC_B_all_svo_calculation       1128
#define IDC_B_optimumU                  1130
#define IDC_CHECK2                      1132
#define IDC_CHECK_ViewResultsPlot       1133
#define IDC_EDIT_LowerLimitOfRadius     1134
#define IDC_EDIT_UpperLimitOfRadius     1135
#define IDC_BUTTON_automatic            1137
#define IDC_BUTTON_checkOptimizationResults 1138
#define IDC_BUTTON_selectFolder         1139
#define IDC_BUTTON1                     1142
#define IDC_BUTTON_camera_calibration   1143
#define IDC_EDIT_ncol                   1144
#define IDC_EDIT_nrow                   1145
#define IDC_RADIO_YED                   1146
#define IDC_RADIO_YY8                   1147
#define IDC_RADIO_9points               1149
#define IDC_RADIO_3points               1150
#define IDC_STATIC_9or3points           1151

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        173
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1152
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
